### ISSUE TITLE
UserController#frequent_users (ActionView::Template::Error) "undefined method `total_pages' for #<User::ActiveRecord_Relation:0xXXXXXX>"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#11]
<table><tr><th>Exception</th><td>undefined method `total_pages&#39; for #&lt;User::ActiveRecord_Relation:0x0056404ca781a8&gt;</td></tr><tr><th>Last Occurrence</th><td>May 21, 2016 18:06:38 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre>[bundle].../gems/activerecord-4.1.14/lib/active_record/relation/delegation.rb:136:in `method_missing'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation/delegation.rb:99:in `method_missing'
[bundle].../gems/will_paginate-3.1.0/lib/will_paginate/view_helpers.rb:73:in `will_paginate'
[bundle].../gems/will_paginate-3.1.0/lib/will_paginate/view_helpers/action_view.rb:33:in `will_paginate'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/views/user/frequent_users.html.erb#L113'>[app].../app/views/user/frequent_users.html.erb:113:in `_app_views_user_frequent_users_html_erb___1077551772712573892_47417081905200'</a>
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:339:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:17:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:99:in `_render_template'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/streaming.rb:217:in `_render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:82:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/as/.rbenv/versions/2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:43:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:238:in `default_render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:165:in `to_html'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:158:in `respond'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:151:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/controllers/user_controller.rb#L23'>[app].../app/controllers/user_controller.rb:23:in `frequent_users'</a>
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `public_send'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `block in halting'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/migration.rb:380:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/handler/webrick.rb:60:in `service'
/home/as/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/home/as/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/home/as/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'</pre>

Fingerprint: `049ea8c94d61c1fecfec240ff59d925634565149`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 21, 2016 18:06:38 +0530</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/user/frequent_users</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>frequent_users</td></tr><tr><th>controller</th><td>user</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>6841261449deba58fdb16c356961d39a</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr><tr><th>_csrf_token</th><td>cY8jUwXODyjJOju2qqZ1iGUW8nUfV+IG4SksfmQzMWw=</td></tr><tr><th>flash</th><td><table><tr><th>discard</th><td>[&quot;alert&quot;]</td></tr><tr><th>flashes</th><td><table><tr><th>alert</th><td>You are already signed in.</td></tr></table></td></tr></table></td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
