### ISSUE TITLE
Api::V1::ProductImagesController#show (ActiveRecord::RecordNotFound) "Couldn't find Product with 'productid'=0"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#12]
<table><tr><th>Exception</th><td>Couldn&#39;t find Product with &#39;productid&#39;=0</td></tr><tr><th>Last Occurrence</th><td>May 31, 2016 21:15:59 +0530</td></tr><tr><th>Count</th><td>22</td></tr></table>

## Stack Trace

<pre>[bundle].../gems/activerecord-4.1.14/lib/active_record/relation/finder_methods.rb:320:in `raise_record_not_found_exception!'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation/finder_methods.rb:429:in `find_one'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation/finder_methods.rb:413:in `find_with_ids'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation/finder_methods.rb:68:in `find'
[bundle].../gems/activerecord-4.1.14/lib/active_record/querying.rb:3:in `find'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/controllers/api/v1/product_images_controller.rb#L7'>[app].../app/controllers/api/v1/product_images_controller.rb:7:in `show'</a>
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `public_send'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `block in halting'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/mapper.rb:45:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:283:in `join'
[bundle].../gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
[bundle].../bin/unicorn:23:in `load'
[bundle].../bin/unicorn:23:in `<main>'</pre>

Fingerprint: `a8f2ee67ae93811589806aaf07be379f7024ede0`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 22, 2016 17:19:27 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.68&#39;&gt;130.211.1.68&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 22, 2016 18:55:54 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.123&#39;&gt;130.211.1.123&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 17:47:40 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.235&#39;&gt;130.211.1.235&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 20:14:13 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.119&#39;&gt;130.211.1.119&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 22:53:41 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.69&#39;&gt;130.211.1.69&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 23:00:15 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.69&#39;&gt;130.211.1.69&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 23:13:00 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.123&#39;&gt;130.211.1.123&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:02:08 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.187&#39;&gt;130.211.1.187&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:15:43 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.120&#39;&gt;130.211.1.120&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 19:21:47 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.60&#39;&gt;130.211.1.60&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 19:55:51 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.123&#39;&gt;130.211.1.123&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 04:44:19 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.250&#39;&gt;130.211.1.250&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 10:39:15 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.240&#39;&gt;130.211.1.240&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 14:21:13 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.116&#39;&gt;130.211.1.116&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 17:31:12 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.185&#39;&gt;130.211.1.185&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 19:40:09 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.187&#39;&gt;130.211.1.187&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 19:51:33 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.114&#39;&gt;130.211.1.114&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 19:55:15 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.44&#39;&gt;130.211.1.44&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 19:57:55 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.0.236&#39;&gt;130.211.0.236&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 26, 2016 08:34:20 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.250&#39;&gt;130.211.1.250&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 26, 2016 11:23:45 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.122&#39;&gt;130.211.1.122&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 31, 2016 21:15:59 +0530</td></tr><tr><th>URL</th><td>[GET] /api/product_images/0</td></tr><tr><th>Params</th><td><table><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>api/v1/product_images</td></tr><tr><th>id</th><td>0</td></tr><tr><th>product_image</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.186&#39;&gt;130.211.1.186&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>
