### ISSUE TITLE
Api::V1::WishlistsController#unmark (NoMethodError) "undefined method `destroy' for nil:NilClass"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#16]
<table><tr><th>Exception</th><td>undefined method `destroy&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>June 01, 2016 10:29:52 +0530</td></tr><tr><th>Count</th><td>18</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/controllers/api/v1/wishlists_controller.rb#L28'>[app].../app/controllers/api/v1/wishlists_controller.rb:28:in `unmark'</a>
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `public_send'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `block in halting'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/mapper.rb:45:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:283:in `join'
[bundle].../gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
[bundle].../bin/unicorn:23:in `load'
[bundle].../bin/unicorn:23:in `<main>'</pre>

Fingerprint: `ff73a0ec2c76e5fecda097c7f4c057c4e3b2d10f`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 07:53:01 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=3749</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>3749</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.41&#39;&gt;130.211.1.41&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 18:25:14 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=880</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>880</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.162&#39;&gt;130.211.1.162&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 12:42:21 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=814</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>814</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.72&#39;&gt;130.211.1.72&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 14:22:29 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=359</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>359</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.62&#39;&gt;130.211.1.62&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>ListUp/in.co.listup.iosapp (5; OS Version 9.3 (Build 13E230))</td></tr><tr><th>Accept Encoding</th><td>gzip;q=1.0, compress;q=0.5</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 14:41:38 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=791</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>791</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.250&#39;&gt;130.211.1.250&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>ListUp/in.co.listup.iosapp (5; OS Version 9.3.2 (Build 13F69))</td></tr><tr><th>Accept Encoding</th><td>gzip;q=1.0, compress;q=0.5</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 16:19:09 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=1370</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>1370</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.69&#39;&gt;130.211.1.69&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 16:19:52 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=1370</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>1370</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.183&#39;&gt;130.211.1.183&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 16:22:17 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=1370</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>1370</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.90&#39;&gt;130.211.1.90&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 16:22:36 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=1370</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>1370</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.183&#39;&gt;130.211.1.183&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 17:04:11 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=2438</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>2438</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.210&#39;&gt;130.211.1.210&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>ListUp/in.co.listup.iosapp (5; OS Version 9.3.2 (Build 13F69))</td></tr><tr><th>Accept Encoding</th><td>gzip;q=1.0, compress;q=0.5</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 13:36:42 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=1470</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>1470</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.114&#39;&gt;130.211.1.114&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 16:37:28 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=3071</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>3071</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.82&#39;&gt;130.211.1.82&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 25, 2016 16:38:02 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=3071</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>3071</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.82&#39;&gt;130.211.1.82&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 27, 2016 18:19:44 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=3826</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>3826</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.146&#39;&gt;130.211.1.146&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 28, 2016 16:23:46 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=2176</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>2176</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.60&#39;&gt;130.211.1.60&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>ListUp/in.co.listup.iosapp (5; OS Version 9.3 (Build 13E230))</td></tr><tr><th>Accept Encoding</th><td>gzip;q=1.0, compress;q=0.5</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 30, 2016 09:11:09 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=3713</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>3713</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.162&#39;&gt;130.211.1.162&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 30, 2016 18:36:38 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=3424</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>3424</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.69&#39;&gt;130.211.1.69&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>June 01, 2016 10:29:52 +0530</td></tr><tr><th>URL</th><td>[DELETE] /api/wishlists/unmark?productid=524</td></tr><tr><th>Params</th><td><table><tr><th>productid</th><td>524</td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/v1/wishlists</td></tr><tr><th>action</th><td>unmark</td></tr><tr><th>wishlist</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.222&#39;&gt;130.211.1.222&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>
