### ISSUE TITLE
Api::V1::ProductsController#index (ActiveRecord::StatementInvalid) "Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1: SELECT `product`.* FROM `product`  WHERE 1=0  ORDER BY field(productid, )"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#23]
<table><tr><th>Exception</th><td>Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#39;)&#39; at line 1: SELECT `product`.* FROM `product`  WHERE 1=0  ORDER BY field(productid, )</td></tr><tr><th>Last Occurrence</th><td>May 23, 2016 17:14:07 +0530</td></tr><tr><th>Count</th><td>4</td></tr></table>

## Stack Trace

<pre>[bundle].../gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
[bundle].../gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
[bundle].../gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
[bundle].../gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/mysql2_adapter.rb:232:in `exec_query'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/mysql2_adapter.rb:240:in `select'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
[bundle].../gems/activerecord-4.1.14/lib/active_record/querying.rb:39:in `find_by_sql'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation.rb:611:in `exec_queries'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation.rb:493:in `load'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation.rb:238:in `to_a'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation/delegation.rb:46:in `map'
[bundle].../gems/active_model_serializers-0.9.5/lib/active_model/array_serializer.rb:43:in `serializable_object'
[bundle].../gems/active_model_serializers-0.9.5/lib/active_model/serializable.rb:12:in `block in as_json'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/active_model_serializers-0.9.5/lib/active_model/serializable.rb:55:in `instrument'
[bundle].../gems/active_model_serializers-0.9.5/lib/active_model/serializable.rb:10:in `as_json'
[bundle].../gems/activesupport-4.1.14/lib/active_support/json/encoding.rb:34:in `encode'
[bundle].../gems/activesupport-4.1.14/lib/active_support/json/encoding.rb:21:in `encode'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:96:in `block in <module:Renderers>'
[bundle].../gems/active_model_serializers-0.9.5/lib/action_controller/serialization.rb:53:in `block (2 levels) in <module:Serialization>'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:39:in `block in _handle_render_options'
/usr/lib/ruby/2.1.0/set.rb:263:in `each_key'
/usr/lib/ruby/2.1.0/set.rb:263:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:36:in `_handle_render_options'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:43:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:260:in `display'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:208:in `api_behavior'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:186:in `rescue in to_format'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:180:in `to_format'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:158:in `respond'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/responder.rb:151:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/controllers/api/v1/products_controller.rb#L30'>[app].../app/controllers/api/v1/products_controller.rb:30:in `index'</a>
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `public_send'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `block in halting'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/mapper.rb:45:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:283:in `join'
[bundle].../gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
[bundle].../bin/unicorn:23:in `load'
[bundle].../bin/unicorn:23:in `<main>'</pre>

Fingerprint: `703942f3901c3ee1cf225366e400184eaea159ab`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 16:56:24 +0530</td></tr><tr><th>URL</th><td>[GET] /api/products?lat=19.1135338&amp;long=72.8938252&amp;from_radius=0&amp;to_radius=5&amp;keyword=Adam%20chairs&amp;new_category=</td></tr><tr><th>Params</th><td><table><tr><th>lat</th><td>19.1135338</td></tr><tr><th>long</th><td>72.8938252</td></tr><tr><th>from_radius</th><td>0</td></tr><tr><th>to_radius</th><td>5</td></tr><tr><th>keyword</th><td>Adam chairs</td></tr><tr><th>new_category</th><td></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/products</td></tr><tr><th>product</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.130&#39;&gt;130.211.1.130&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 17:01:52 +0530</td></tr><tr><th>URL</th><td>[GET] /api/products?lat=19.1135338&amp;long=72.8938252&amp;from_radius=0&amp;to_radius=5&amp;keyword=True%20Black%20portrait&amp;new_category=</td></tr><tr><th>Params</th><td><table><tr><th>lat</th><td>19.1135338</td></tr><tr><th>long</th><td>72.8938252</td></tr><tr><th>from_radius</th><td>0</td></tr><tr><th>to_radius</th><td>5</td></tr><tr><th>keyword</th><td>True Black portrait</td></tr><tr><th>new_category</th><td></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/products</td></tr><tr><th>product</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.247&#39;&gt;130.211.1.247&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 17:08:42 +0530</td></tr><tr><th>URL</th><td>[GET] /api/products?id=564&amp;lat=28.6508353&amp;long=77.267595</td></tr><tr><th>Params</th><td><table><tr><th>id</th><td>564</td></tr><tr><th>lat</th><td>28.6508353</td></tr><tr><th>long</th><td>77.267595</td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/products</td></tr><tr><th>product</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.70&#39;&gt;130.211.1.70&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 23, 2016 17:14:07 +0530</td></tr><tr><th>URL</th><td>[GET] /api/products?lat=19.113693&amp;long=72.893651&amp;from_radius=0&amp;to_radius=100&amp;keyword=Bullet%20bike&amp;category_ids=</td></tr><tr><th>Params</th><td><table><tr><th>lat</th><td>19.113693</td></tr><tr><th>long</th><td>72.893651</td></tr><tr><th>from_radius</th><td>0</td></tr><tr><th>to_radius</th><td>100</td></tr><tr><th>keyword</th><td>Bullet bike</td></tr><tr><th>category_ids</th><td></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/products</td></tr><tr><th>product</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.95&#39;&gt;130.211.1.95&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>
