### ISSUE TITLE
CampaignsController#new (ActionView::Template::Error) "undefined method `campaign_index_path' for #<#<Class:0xXXXXXX>:0xXXXXXX>"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#35]
<table><tr><th>Exception</th><td>undefined method `campaign_index_path&#39; for #&lt;#&lt;Class:0x0000000ba34a20&gt;:0x0000000ba2ff20&gt;</td></tr><tr><th>Last Occurrence</th><td>May 24, 2016 16:00:43 +0530</td></tr><tr><th>Count</th><td>12</td></tr></table>

## Stack Trace

<pre>[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/polymorphic_routes.rb:142:in `polymorphic_url'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/polymorphic_routes.rb:148:in `polymorphic_path'
[bundle].../gems/actionview-4.1.14/lib/action_view/helpers/form_helper.rb:452:in `apply_form_for_options!'
[bundle].../gems/actionview-4.1.14/lib/action_view/helpers/form_helper.rb:425:in `form_for'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/views/campaigns/_form.html.erb#L6'>[app].../app/views/campaigns/_form.html.erb:6:in `_app_views_campaigns__form_html_erb___3088768318913332380_96905520'</a>
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:339:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/partial_renderer.rb:278:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/renderer.rb:47:in `render_partial'
[bundle].../gems/actionview-4.1.14/lib/action_view/helpers/rendering_helper.rb:35:in `render'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/views/campaigns/new.html.erb#L3'>[app].../app/views/campaigns/new.html.erb:3:in `_app_views_campaigns_new_html_erb__2398891790051185429_97611740'</a>
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:339:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/template_renderer.rb:17:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:99:in `_render_template'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/streaming.rb:217:in `_render_template'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:82:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:43:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `public_send'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `block in halting'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:283:in `join'
[bundle].../gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
[bundle].../bin/unicorn:23:in `load'
[bundle].../bin/unicorn:23:in `<main>'</pre>

Fingerprint: `929e9466daf148d24ec60d8f446be607af367b1c`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:36:02 +0530</td></tr><tr><th>URL</th><td>[GET] /campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>8d4373eca727a95a0f43e039c4860c4d</td></tr><tr><th>administrator_return_to</th><td>/administrator/login_home</td></tr><tr><th>warden.user.administrator.key</th><td>[[8], &quot;$2a$10$0ykvYbVkqG7DkG4Ct5naNe&quot;]</td></tr><tr><th>_csrf_token</th><td>E81rtKGWpwscw1hZaid81ncKPPGiw9QiAS/WVXQkw9Q=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.40&#39;&gt;130.211.1.40&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:36:09 +0530</td></tr><tr><th>URL</th><td>[GET] /campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>8d4373eca727a95a0f43e039c4860c4d</td></tr><tr><th>administrator_return_to</th><td>/administrator/login_home</td></tr><tr><th>warden.user.administrator.key</th><td>[[8], &quot;$2a$10$0ykvYbVkqG7DkG4Ct5naNe&quot;]</td></tr><tr><th>_csrf_token</th><td>E81rtKGWpwscw1hZaid81ncKPPGiw9QiAS/WVXQkw9Q=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.114&#39;&gt;130.211.1.114&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:38:00 +0530</td></tr><tr><th>URL</th><td>[GET] /campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4caf02aa3431441c1ab88add64863f36</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>flash</th><td><table><tr><th>discard</th><td>[&quot;notice&quot;]</td></tr><tr><th>flashes</th><td><table><tr><th>notice</th><td>Signed in successfully.</td></tr></table></td></tr></table></td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.120&#39;&gt;130.211.1.120&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:40:42 +0530</td></tr><tr><th>URL</th><td>[GET] /campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>8d4373eca727a95a0f43e039c4860c4d</td></tr><tr><th>administrator_return_to</th><td>/administrator/login_home</td></tr><tr><th>warden.user.administrator.key</th><td>[[8], &quot;$2a$10$0ykvYbVkqG7DkG4Ct5naNe&quot;]</td></tr><tr><th>_csrf_token</th><td>E81rtKGWpwscw1hZaid81ncKPPGiw9QiAS/WVXQkw9Q=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.215&#39;&gt;130.211.1.215&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:41:44 +0530</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4004198d530c4c5e4b94fe48b5ee1ae0</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr><tr><th>_csrf_token</th><td>9Jhm4x4hHfytCCG1A0WG6V2JKY/1G+f96KJMrm+gRtg=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:44:32 +0530</td></tr><tr><th>URL</th><td>[GET] /campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4caf02aa3431441c1ab88add64863f36</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>flash</th><td><table><tr><th>discard</th><td>[&quot;notice&quot;]</td></tr><tr><th>flashes</th><td><table><tr><th>notice</th><td>Signed in successfully.</td></tr></table></td></tr></table></td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.125&#39;&gt;130.211.1.125&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:49:41 +0530</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4004198d530c4c5e4b94fe48b5ee1ae0</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr><tr><th>_csrf_token</th><td>9Jhm4x4hHfytCCG1A0WG6V2JKY/1G+f96KJMrm+gRtg=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:52:22 +0530</td></tr><tr><th>URL</th><td>[GET] /campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4caf02aa3431441c1ab88add64863f36</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>flash</th><td><table><tr><th>discard</th><td>[&quot;notice&quot;]</td></tr><tr><th>flashes</th><td><table><tr><th>notice</th><td>Signed in successfully.</td></tr></table></td></tr></table></td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.88&#39;&gt;130.211.1.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:57:03 +0530</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4004198d530c4c5e4b94fe48b5ee1ae0</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr><tr><th>_csrf_token</th><td>9Jhm4x4hHfytCCG1A0WG6V2JKY/1G+f96KJMrm+gRtg=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 15:59:14 +0530</td></tr><tr><th>URL</th><td>[GET] /campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4caf02aa3431441c1ab88add64863f36</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>flash</th><td><table><tr><th>discard</th><td>[&quot;notice&quot;]</td></tr><tr><th>flashes</th><td><table><tr><th>notice</th><td>Signed in successfully.</td></tr></table></td></tr></table></td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.88&#39;&gt;130.211.1.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 24, 2016 16:00:43 +0530</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/campaigns/new</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>new</td></tr><tr><th>controller</th><td>campaigns</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>4004198d530c4c5e4b94fe48b5ee1ae0</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr><tr><th>_csrf_token</th><td>9Jhm4x4hHfytCCG1A0WG6V2JKY/1G+f96KJMrm+gRtg=</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
