### ISSUE TITLE
NilClass# (SyntaxError) "/home/as/listup_api/app/controllers/user_controller.rb:246: syntax error, unexpected end-of-input, expecting keyword_end"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#4]
<table><tr><th>Exception</th><td>/home/as/listup_api/app/controllers/user_controller.rb:246: syntax error, unexpected end-of-input, expecting keyword_end</td></tr><tr><th>Last Occurrence</th><td>May 20, 2016 12:59:27 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre>[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:443:in `load'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:443:in `block in load_file'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:633:in `new_constants_in'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:442:in `load_file'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:342:in `require_or_load'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:480:in `load_missing_constant'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:180:in `const_missing'
[bundle].../gems/activesupport-4.1.14/lib/active_support/inflector/methods.rb:238:in `const_get'
[bundle].../gems/activesupport-4.1.14/lib/active_support/inflector/methods.rb:238:in `block in constantize'
[bundle].../gems/activesupport-4.1.14/lib/active_support/inflector/methods.rb:236:in `each'
[bundle].../gems/activesupport-4.1.14/lib/active_support/inflector/methods.rb:236:in `inject'
[bundle].../gems/activesupport-4.1.14/lib/active_support/inflector/methods.rb:236:in `constantize'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:552:in `get'
[bundle].../gems/activesupport-4.1.14/lib/active_support/dependencies.rb:583:in `constantize'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:78:in `controller_reference'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:68:in `controller'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:46:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/migration.rb:380:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/handler/webrick.rb:60:in `service'
/home/as/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/home/as/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/home/as/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'</pre>

Fingerprint: `6ae26d580148bc84d79bb7c8a43df0da6f1ffc9c`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 20, 2016 12:59:27 +0530</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/user?start_date=2016%2F05%2F13&amp;end_date=2016%2F05%2F20&amp;keyword=&amp;status=0&amp;driver_penalty_info_list=Show+Info</td></tr><tr><th>Params</th><td><table></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>11317272a919f59dc15997f3e994376a</td></tr><tr><th>administrator_return_to</th><td>/</td></tr><tr><th>warden.user.administrator.key</th><td>[[9], &quot;$2a$10$sWNULrTPRbBhOfi/8D2Jbe&quot;]</td></tr></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
