### ISSUE TITLE
Api::V1::ProductsController#index (NoMethodError) "undefined method `height' for #<Product:0xXXXXXX>"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#6]
<table><tr><th>Exception</th><td>undefined method `height&#39; for #&lt;Product:0x0000000b45fe38&gt;</td></tr><tr><th>Last Occurrence</th><td>May 20, 2016 15:11:51 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre>[bundle].../gems/activemodel-4.1.14/lib/active_model/attribute_methods.rb:435:in `method_missing'
[bundle].../gems/activerecord-4.1.14/lib/active_record/attribute_methods.rb:213:in `method_missing'
[bundle].../gems/activemodel-4.1.14/lib/active_model/serialization.rb:108:in `block in serializable_hash'
[bundle].../gems/activemodel-4.1.14/lib/active_model/serialization.rb:108:in `each'
[bundle].../gems/activemodel-4.1.14/lib/active_model/serialization.rb:108:in `serializable_hash'
[bundle].../gems/activerecord-4.1.14/lib/active_record/serialization.rb:17:in `serializable_hash'
[bundle].../gems/activemodel-4.1.14/lib/active_model/serializers/json.rb:99:in `as_json'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:140:in `map'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:140:in `as_json'
[bundle].../gems/activerecord-4.1.14/lib/active_record/relation.rb:243:in `as_json'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:159:in `each'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:159:in `map'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:159:in `as_json'
[bundle].../gems/activesupport-4.1.14/lib/active_support/json/encoding.rb:34:in `encode'
[bundle].../gems/activesupport-4.1.14/lib/active_support/json/encoding.rb:21:in `encode'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/serializable_resource.rb:8:in `to_json'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:69:in `block (3 levels) in notify'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:334:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:334:in `block (2 levels) in simple'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:22:in `call'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:22:in `block (3 levels) in instrument_rendering'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:79:in `block in notify_render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:78:in `notify_render'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:95:in `block in tag_logger'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:95:in `tag_logger'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:438:in `instance_exec'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:438:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:333:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:333:in `block in simple'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:96:in `block in <module:Renderers>'
[bundle].../gems/active_model_serializers-0.10.0/lib/action_controller/serialization.rb:52:in `block (2 levels) in <module:Serialization>'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:39:in `block in _handle_render_options'
/usr/lib/ruby/2.1.0/set.rb:263:in `each_key'
/usr/lib/ruby/2.1.0/set.rb:263:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:36:in `_handle_render_options'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:43:in `render'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/controllers/api/v1/products_controller.rb#L18'>[app].../app/controllers/api/v1/products_controller.rb:18:in `index'</a>
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `public_send'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `block in halting'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/mapper.rb:45:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
[bundle].../gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
[bundle].../bin/unicorn:23:in `load'
[bundle].../bin/unicorn:23:in `<main>'</pre>

Fingerprint: `613204f57d463d16f243b9bafab26b7499778efb`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>May 20, 2016 15:11:51 +0530</td></tr><tr><th>URL</th><td>[GET] /api/products?id=14218&amp;lat=28.4429732&amp;long=77.0603674</td></tr><tr><th>Params</th><td><table><tr><th>id</th><td>14218</td></tr><tr><th>lat</th><td>28.4429732</td></tr><tr><th>long</th><td>77.0603674</td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/products</td></tr><tr><th>product</th><td><table></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.251&#39;&gt;130.211.1.251&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.1.2</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>
