### ISSUE TITLE
Api::V1::SharedItemsController#create (NoMethodError) "undefined method `api_shared_item_url' for #<Api::V1::SharedItemsController:0xXXXXXX>"

### ISSUE THREAD

**Issue by ashu1061** [ashu1061/footy#76]
<table><tr><th>Exception</th><td>undefined method `api_shared_item_url&#39; for #&lt;Api::V1::SharedItemsController:0x0000000f2c7ce8&gt;</td></tr><tr><th>Last Occurrence</th><td>June 02, 2016 14:21:59 +0530</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace

<pre>[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/polymorphic_routes.rb:142:in `polymorphic_url'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/url_for.rb:159:in `url_for'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:99:in `_process_options'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/streaming.rb:200:in `_process_options'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:38:in `block in _handle_render_options'
/usr/lib/ruby/2.1.0/set.rb:263:in `each_key'
/usr/lib/ruby/2.1.0/set.rb:263:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:36:in `_handle_render_options'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[bundle].../gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:43:in `render'
<a href='https://github.com/ashu1061/footy/blob/0c0882f21f5ccecfc69f4546115feec053ca3071/app/controllers/api/v1/shared_items_controller.rb#L12'>[app].../app/controllers/api/v1/shared_items_controller.rb:12:in `create'</a>
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:495:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:306:in `block (2 levels) in halting'
[bundle].../gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `public_send'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:452:in `block in make_lambda'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:305:in `block in halting'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:494:in `block in around'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:502:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.14/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.14/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/mapper.rb:45:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/routing/route_set.rb:692:in `call'
[bundle].../bundler/gems/party_foul-7467951b0c17/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/cookies.rb:562:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.14/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.14/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.14/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/actionpack-4.1.14/lib/action_dispatch/middleware/static.rb:84:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.14/lib/rails/application.rb:144:in `call'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
[bundle].../gems/unicorn-5.1.0/lib/unicorn/http_server.rb:283:in `join'
[bundle].../gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
[bundle].../bin/unicorn:23:in `load'
[bundle].../bin/unicorn:23:in `<main>'</pre>

Fingerprint: `3ec4f976c76eb66a5482ba740f0c183afff6dbc1`

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>June 01, 2016 15:39:50 +0530</td></tr><tr><th>URL</th><td>[POST] /api/users/15152/shared_items</td></tr><tr><th>Params</th><td><table><tr><th>shared_item</th><td><table><tr><th>media</th><td>1</td></tr><tr><th>productId</th><td>831</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>api/v1/shared_items</td></tr><tr><th>user_id</th><td>15152</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.69&#39;&gt;130.211.1.69&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>June 01, 2016 16:06:56 +0530</td></tr><tr><th>URL</th><td>[POST] /api/users/15152/shared_items</td></tr><tr><th>Params</th><td><table><tr><th>shared_item</th><td><table><tr><th>media</th><td>4</td></tr><tr><th>productId</th><td>253</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>api/v1/shared_items</td></tr><tr><th>user_id</th><td>15152</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.116&#39;&gt;130.211.1.116&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>June 02, 2016 02:48:38 +0530</td></tr><tr><th>URL</th><td>[POST] /api/users/16738/shared_items</td></tr><tr><th>Params</th><td><table><tr><th>shared_item</th><td><table><tr><th>media</th><td>3</td></tr><tr><th>productId</th><td>145</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>api/v1/shared_items</td></tr><tr><th>user_id</th><td>16738</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.59&#39;&gt;130.211.1.59&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>June 02, 2016 13:44:57 +0530</td></tr><tr><th>URL</th><td>[POST] /api/users/16008/shared_items</td></tr><tr><th>Params</th><td><table><tr><th>shared_item</th><td><table><tr><th>media</th><td>2</td></tr><tr><th>productId</th><td>1028</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>api/v1/shared_items</td></tr><tr><th>user_id</th><td>16008</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.151&#39;&gt;130.211.1.151&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>

**Comment by ashu1061** [comment]
<table><tr><th>Occurred At</th><td>June 02, 2016 14:21:59 +0530</td></tr><tr><th>URL</th><td>[POST] /api/users/16823/shared_items</td></tr><tr><th>Params</th><td><table><tr><th>shared_item</th><td><table><tr><th>media</th><td>3</td></tr><tr><th>productId</th><td>1230</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>api/v1/shared_items</td></tr><tr><th>user_id</th><td>16823</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/130.211.1.41&#39;&gt;130.211.1.41&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>okhttp/3.2.0</td></tr><tr><th>Accept Encoding</th><td>gzip</td></tr><tr><th>Accept</th><td>application/json</td></tr></table></td></tr></table>
